modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
[[mods]]
modId = "refinedcooking"
version = "${file.jarVersion}"
displayName = "Refined Cooking"
logoFile = "logo.png"
authors = "ItsSebastrn"
description = '''
A mod to bridge Cooking For Blockheads with Refined Storage
'''
[[dependencies.refinedcooking]]
modId = "refinedstorage"
mandatory = true
versionRange = "[1.12.0,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.refinedcooking]]
modId = "cookingforblockheads"
mandatory = true
versionRange = "[16.0.0,)"
ordering = "BEFORE"
side = "BOTH"
#[[dependencies.refinedcooking]]
#modId = "sebastrnlib"
#mandatory = true
#versionRange = "[2.0.0,)"
#ordering = "AFTER"
#side = "BOTH"